# 1) Order of rules goes from top to bottom.
# 2) Also rules has to be specific, not general, cause only first rule matching
# 3) .sops.yaml has to be inside root folder of your project

creation_rules:
  # 🔐 Admin
  - path_regex: ^secrets/(global|backend)/.*$
    encrypted_regex: '.*'
    key_groups:
      - age:
          - age1x20mffeqzuecsy2gv359yyd3txm6k46xhxx8u3x2v428vcwffyaq0txw0p


  # 🔐 Dev
  - path_regex: ^secrets/dev/.*$
    encrypted_regex: '.*'
    key_groups:
      - age:
          - age1pmkw2pnmmdya9n8m327dnqfs06ws3jgsy44mcau4w7a7fee2a5lq8dq94k

  # 🔐 Prod
  - path_regex: ^secrets/prod/.*$
    encrypted_regex: '.*'
    key_groups:
      - age:
          - age1ncdepydhznaeevp8vf9scq7rq7tplk4k9ech3ck6wlqhfg360pkshm80w7
        