- name: Установка Docker и запуск контейнера
  hosts: 
  become: yes
  tasks:

    


   

    - name: Build Docker image from service folder
      docker_image:
        name: "{{ service }}_image"
        build:
          path: "{{ docker_context_path }}"
        source: build
        force_source: true
        force_tag: true

    - name: Launch/Relaunch Docker container
      docker_container:
        name: nginx_container
        image: "{{ docker_image }}"
        state: started
        restart_policy: always
        env_file: "/.env"
        ports:
          - "80:80"
          - "443:443"
        recreate: yes