ansible_user: melnikov
ansible_ssh_port: 22
ansible_host_key_checking: false
ansible_python_interpreter: /usr/bin/python3

work_dir: "{{ lookup('env', 'WORK_DIR') }}" 
secret_env_file: "{{ work_dir }}/secrets/{{ env }}/{{ app }}/{{ service }}/secret.env"
secret_ops_folder: "{{ work_dir }}/secrets/ops"

# Docker
docker_build_path: "{{ work_dir }}/projects/{{ app }}/{{ service }}"
image_name: "{{ service }}_image"
container_name: "{{ service }}_container"